name: Build ImGui for Ubuntu
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}
        - uses: abel0b/setup-premake@v2.4
          with:
            version: "5.0.0-beta2"
        - uses: actions/setup-node@v4
          with:
              node-version: 'latest'
        - run: node tools/brief/main.js
        - name: Run Premake
          run: |
            premake5 gmake2
            cd dll/
            make
        - run: npm install
          working-directory: ./tools/bundle/
        - run: node tools/bundle/main.js
        - name: Upload library
          uses: actions/upload-artifact@v3
          with:
            name: output
            path: package.yymps